server:
  port: 9001
spring:
  servlet:
    multipart:
      max-file-size:
        100MB
      max-request-size:
        100MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://192.168.43.128:30000/container?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 369369
    driver-class-name: com.mysql.jdbc.Driver

